package com.GenericUtility;

import java.time.LocalDateTime;
import java.util.Random;
import java.util.UUID;
/**
 * UUID means Universally Unique Identifier.
 * UUID is a Java utility, not a Selenium class. Selenium simply uses the unique value generated by Java.
 * java.util.UUID is commonly used when you need to generate a unique value,
 *  especially for creating unique usernames, email IDs, campaign names, contact names, etc.
 */

public class JavaUtility
//TIMESTAMP
/**
 * This method is used to capture Local date and time of the system
 * is commonly used to generate a unique value based on the current date and time.A timestamp tells you when something happened.
 *  @return String

 */
{
	public String timeStamp()

	{
		//return	LocalDateTime.now().toString().replaceAll(":", "_");

		String time =  LocalDateTime.now().toString().replace(":","_");
		return time;
	}
	//Generate Random number
	/**
	 * This method is used to generate random number.
       
	 * @return int
	 */
	 public int generateRandomNumber()
	 {
		 Random random = new Random();
		 int randomvalue = random.nextInt(1000000);
		 return randomvalue;
	 }
	 //Generate Random Data
	 
	 /**
	  * This method is used to generate random string data
	  * @return String
	  */
	 public String generateRandomData()
	 {
		 String data = UUID.randomUUID().toString().replaceAll("[^a-zA-Z]", "");
			
			return data;
		}
	 }

